 
      APP_ENVIRONMENT_ONLY: "false"
 
      CACHE_DRIVER: "redis"
 
      SESSION_DRIVER: "redis"
 
      QUEUE_DRIVER: "redis"
 
      REDIS_HOST: "cache"
 
      DB_HOST: "database"
 
      DB_PORT: "3306"
 
networks:
 
  default:
 
    ipam:
 
      config:
 
        - subnet: 172.20.0.0/16
